version: '3'

volumes:
  data:

services:
  app:
    restart: on-failure
    image: pdouble16/adventuregame:latest
    environment:
      SPRING_PROFILES_ACTIVE: "stage"
    ports:
    - 10222:8080
    volumes:
    - data:/data
