version: '3'

volumes:
  data:

services:
  app:
    restart: on-failure
    image: ${IMAGE:-double16/adventuregame:latest}
#    healthcheck:
#      test: "curl -s -O /dev/null http://localhost:8080/actuator/health || exit 1"
    environment:
      SPRING_PROFILES_ACTIVE: "stage"
    ports:
    - 8080
    volumes:
    - data:/home/cnb
