version: 2
jobs:
  build:
    working_directory: ~/adventuregame
    environment:
      - TERM=dumb
    docker:
      - image: openjdk:11.0.6-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - adventuregame-{{ .Branch }}-{{ checksum "build.gradle" }}
            - adventuregame-{{ .Branch }}
            - adventuregame-

      - run:
          name: codenarc
          command: ./gradlew codenarcMain --stacktrace
      - run:
          name: Open Source Vuln
          command: ./gradlew dependencyCheckAggregate --stacktrace
      - run:
          name: Unit Tests
          command: ./gradlew test cloverGenerateReport --stacktrace
      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/reports/clover
          destination: coverage

      - save_cache:
          key: adventuregame-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - "~/.gradle"
