version: 2
jobs:
  build:
    working_directory: ~/adventuregame
    environment:
      - TERM=dumb
    docker:
      - image: openjdk:14.0.1-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - adventuregame-{{ .Branch }}-{{ checksum "build.gradle" }}
            - adventuregame-{{ .Branch }}
            - adventuregame-

      - run:
          name: codenarc
          command: ./gradlew codenarcMain --stacktrace --no-daemon
# Takes too long, >10m
#      - run:
#          name: Open Source Vuln
#          command: ./gradlew dependencyCheckAggregate --stacktrace --no-daemon
      - run:
          name: Unit Tests
          command: ./gradlew test cloverGenerateReport --stacktrace --no-daemon
      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/reports/clover
          destination: coverage

      - save_cache:
          key: adventuregame-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - "~/.gradle"
